import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { app } from "electron";
import {
  enabledUserSkillIds,
  isValidSkillId,
  parseSkillFrontmatter,
  userSkillFilterNames,
  USER_PLUGIN_NAME,
  type UserSkillInfo,
} from "../shared/user-skills";

/**
 * The user's own skills live in an app-owned local plugin:
 *
 *   <userData>/user-skills/
 *     .claude-plugin/plugin.json   ← generated by us (name = "my-skills")
 *     skills/<skill-id>/SKILL.md   ← dropped in by the user
 *
 * The folder is created lazily; «Открыть папку» in Settings reveals it. Skills
 * are scanned fresh on every run/list, so a newly dropped folder just works.
 */

export function userSkillsRoot(): string {
  return join(app.getPath("userData"), "user-skills");
}

/** Create the plugin skeleton (idempotent) so the folder is drop-in ready. */
export async function ensureUserSkillsPlugin(): Promise<string> {
  const root = userSkillsRoot();
  await mkdir(join(root, "skills"), { recursive: true });
  const manifest = join(root, ".claude-plugin", "plugin.json");
  if (!existsSync(manifest)) {
    await mkdir(join(root, ".claude-plugin"), { recursive: true });
    await writeFile(
      manifest,
      JSON.stringify(
        {
          name: USER_PLUGIN_NAME,
          version: "1.0.0",
          description: "Личные скиллы пользователя Wello Code",
        },
        null,
        2,
      ),
      "utf8",
    );
  }
  return root;
}

/** Scan the skills dir: every subfolder with a readable SKILL.md is a skill. */
export async function listUserSkills(): Promise<UserSkillInfo[]> {
  const skillsDir = join(userSkillsRoot(), "skills");
  let entries;
  try {
    entries = await readdir(skillsDir, { withFileTypes: true });
  } catch {
    return [];
  }
  const out: UserSkillInfo[] = [];
  for (const e of entries) {
    if (!e.isDirectory() || !isValidSkillId(e.name)) continue;
    try {
      const raw = await readFile(join(skillsDir, e.name, "SKILL.md"), "utf8");
      const fm = parseSkillFrontmatter(raw);
      out.push({
        id: e.name,
        name: fm.name || e.name,
        description: fm.description ?? "",
      });
    } catch {
      // No SKILL.md → not a skill folder; skip silently.
    }
  }
  return out.sort((a, b) => a.id.localeCompare(b.id));
}

/**
 * Everything a run needs for the user's own skills: the plugin dir (when at
 * least one skill is enabled) and the explicit filter names. Scanned fresh per
 * run so drops/removals apply immediately.
 */
export async function resolveUserSkills(
  saved: Record<string, boolean> | null | undefined,
): Promise<{ pluginDir: string | null; skills: string[] }> {
  const found = await listUserSkills();
  const enabled = enabledUserSkillIds(found, saved);
  if (enabled.length === 0) return { pluginDir: null, skills: [] };
  // The skeleton also heals a hand-made folder missing its plugin.json — the
  // engine rejects a plugin dir without a manifest.
  await ensureUserSkillsPlugin();
  return { pluginDir: userSkillsRoot(), skills: userSkillFilterNames(enabled) };
}
